### ISSUE TITLE
can we move away from protobuf

### ISSUE THREAD

**Issue by susgaming123** [RavEngine/RavEngine#8]
here is the reason why:
![image](https://github.com/RavEngine/RavEngine/assets/118131071/5cdf34a6-4a70-4d58-8811-6c1a3e341da5)

**Comment by susgaming123** [comment]
zpp::bits go brrrrrrr

**Comment by Ravbug** [comment]
RavEngine uses protobuf because [Valve GameNetworkingSockets](https://github.com/ValveSoftware/GameNetworkingSockets),  our networking library, uses it. You should open an issue there if you want them to drop protobuf in favor of something else.  

However, you shouldn't have to interact with protobuf at all when using RavEngine.

**Comment by susgaming123** [comment]
ah my bad, i will open an issue there. thank!

**Comment by Ravbug** [comment]
GNS uses protobuf internally, which is why it's in our repo. RavEngine does not directly use it.

To remove protobuf, either GNS would need to stop using protobuf, or RavEngine would need to switch to an entirely different networking library.

**Comment by susgaming123** [comment]
ah welp i made an issue about it but i think it will be dismissed because of multiple reasons:
https://github.com/ValveSoftware/GameNetworkingSockets/issues/293
